on: [push]

jobs:
  DocTide_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: run DocTide action
        id: doctide
        uses: BrandtBoys/Bachelor@v1
        with:
          testing: true